### ISSUE TITLE
installation instruction

### ISSUE THREAD

**Issue by zhanxw** [estfernan/boost#1]
Please add 

    devtools::install_github("xzhoulab/SPARK")

In the installation instruction. Or I experienced this error:

    ERROR: dependency ‘SPARK’ is not available for package ‘boost’

**Comment by estfernan** [comment]
I have added the installation instructions, but does this error come up when installing the package or using any SPARK functions? If it is the first, then I will have to also remove it from the `DESCRIPTION` file.

**Comment by estfernan** [comment]
Installation instructions have been added and `SPARK` dependency has been removed from `DESCRIPTION` file. A message will be displayed to users to install `SPARK` from Github when wanting to use the *SPARK* model.
