### ISSUE TITLE
Add two new functions

### ISSUE THREAD

**Issue by Xijiang1997** [estfernan/boost#5]
Hi Esteban! As Dr. Li's suggestions, we need to add some new functions in this package. I put a new R script under the path boost/R. Could you please add them in the package? Thanks!

One is rank.aggregation function: aggregate rankings from p base rankers to generate an aggregated ranking from R package “TopKLists”. The input data file should be a p-value table with n observations and (p + 1) variables, where the first column is the gene name and other columns are methods (base rankers). Input K is to sort out top-K genes in each base ranker. method is the rank aggregation method and ties.method is a character string specifying how ties are treated (see details in R function “rank()”). The output is a table with genes and their rank.

The other one is compute.metrics function, which is used to calculate performance of SV gene identification on simulated data. Inputs are: 1. predictor: a vector of p-values or Bayes factors; 2. truth: a logical vector, which is the ground truth corresponding to the predictor; 3. predictor.type = c('BF', 'p-value'); 4. threshold: the threshold to defining SV gene. The output is a list including six performance metrics. 

If you have any questions, just email me. Thanks!

**Comment by estfernan** [comment]
Hi Xi! Thank you for adding these two new functions. I have incorporated them into the package and I just have a couple of questions before we can close this issue. For both functions: 1) Should there be any references that we should include in the documentation? 2) Is the documentation correct and/or should we add something else?

**Comment by Xijiang1997** [comment]
Hi Esteban! Thanks for updating it! 
1) We should refer all packages used in these two functions, like Hmisc, topKlists and pROC, and also this paper: 
Xue Li, Xinlei Wang, Guanghua Xiao, A comparative study of rank aggregation methods for partial and top ranked lists in genomic applications, Briefings in Bioinformatics, Volume 20, Issue 1, January 2019, Pages 178–189, https://doi.org/10.1093/bib/bbx101
2) The documentation looks good to me.
Thanks!

**Comment by estfernan** [comment]
Hi Xi, I have added the references (paper and package dependencies) to both of the functions.
