### ISSUE TITLE
Issues of BOOST.GP outputs

### ISSUE THREAD

**Issue by Xijiang1997** [estfernan/boost#6]
Hi! I found some issues of the BOOST.GP function. 
1. Could you please change the default setting of n.iter from 10000 to 2000 in order to reduce the running time of it? 
2. I tried BOOST.GP on several genes. The outputs of normalized gene expression levels are NA. Could you please fix this issue? Here is the outputs of BOOST.GP function:
Call:
BOOST.GP(abs.expr = abs_expr, spots = sample_info, size.factor = size_factor, 
    gene.name = "Doc2g", n.iter = 3000)

Model: BOOST-GP 

Parameters:
                                  Estimate Std. Error Lower 95% CI Upper 95% CI
Dispersion                            9.82       9.39          2.2        37.53
Normalized gene expression levels      NaN         NA           NA           NA
Kernel                                0.57       0.17          0.0         0.71

Bayes Factor in favor of a spatially variable gene: 220.495798041392
p-value: 6.58623527473885e-98

Thanks!

**Comment by estfernan** [comment]
Hi Xi! 

Your updated file has been incorporated into the package. Please let me know if this issue is now fixed. Thanks!
